name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: bigazy
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: mydb
        options: >-
          --health-cmd "pg_isready -U bigazy" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

      redis:
        image: redis:7
        ports: ["6379:6379"]

    steps:
      - name: 🔄 Checkout code
        uses: actions/checkout@v3

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 📦 Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: 🧪 Run tests
        run: |
          pytest
          
      - name: 🐳 Build Docker image
        run: |
          docker build . -t myapp:latest
